import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter, Almarai } from "next/font/google";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const almarai = Almarai({
    subsets: ["arabic"],
    weight: ["300", "400", "700", "800"],
});

export const metadata = {
    title: "",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ar" dir="rtl">
            <body className={almarai.className}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
